table eleitorado_cruzado
	lineageTag: c22b1aff-2ba5-460c-abac-922444ef0ce2

	column DT_GERACAO
		dataType: dateTime
		formatString: Long Date
		lineageTag: af6343f2-f684-46c1-b0ac-5cf8806dd539
		summarizeBy: none
		sourceColumn: DT_GERACAO

		variation Variation
			isDefault
			relationship: 7e73357d-84c3-43cd-904f-25c480beadb4
			defaultHierarchy: LocalDateTable_3e772eb3-5135-4865-a556-e068b8abf7a7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HH_GERACAO
		dataType: dateTime
		formatString: Long Time
		lineageTag: d5b11d31-754b-420f-b873-5902c404d4dd
		summarizeBy: none
		sourceColumn: HH_GERACAO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column AA_ELEICAO
		dataType: int64
		formatString: 0
		lineageTag: 8221d082-ac44-426b-bd0a-dae8754ee14e
		summarizeBy: sum
		sourceColumn: AA_ELEICAO

		annotation SummarizationSetBy = Automatic

	column SG_UF
		dataType: string
		lineageTag: 4a7b61f2-6d94-4901-a6f4-50c0b2539a67
		summarizeBy: none
		sourceColumn: SG_UF

		annotation SummarizationSetBy = Automatic

	column CD_GENERO
		dataType: string
		lineageTag: 83785bbb-1f56-4f68-ba45-983743d241db
		summarizeBy: none
		sourceColumn: CD_GENERO

		annotation SummarizationSetBy = Automatic

	column DS_GENERO
		dataType: string
		lineageTag: 7f839863-9ff0-41da-83a7-46838f2545f3
		summarizeBy: none
		sourceColumn: DS_GENERO

		annotation SummarizationSetBy = Automatic

	column CD_ESTADO_CIVIL
		dataType: string
		lineageTag: ab1bcec3-4abe-49ea-b704-1346de4fdf8c
		summarizeBy: none
		sourceColumn: CD_ESTADO_CIVIL

		annotation SummarizationSetBy = Automatic

	column DS_ESTADO_CIVIL
		dataType: string
		lineageTag: fd4b8563-1cc5-4fe5-94c0-3d119df60f38
		summarizeBy: none
		sourceColumn: DS_ESTADO_CIVIL

		annotation SummarizationSetBy = Automatic

	column CD_FAIXA_ETARIA
		dataType: string
		lineageTag: b8f7a5ff-5664-4c71-980b-5d6eac403f75
		summarizeBy: none
		sourceColumn: CD_FAIXA_ETARIA

		annotation SummarizationSetBy = Automatic

	column DS_FAIXA_ETARIA
		dataType: string
		lineageTag: f41eafb5-4fe7-4c3d-92ca-41c6d568c934
		summarizeBy: none
		sourceColumn: DS_FAIXA_ETARIA

		annotation SummarizationSetBy = Automatic

	column CD_GRAU_ESCOLARIDADE
		dataType: string
		lineageTag: 3c8764bb-adb4-42cb-bd22-e96bc98cb5cb
		summarizeBy: none
		sourceColumn: CD_GRAU_ESCOLARIDADE

		annotation SummarizationSetBy = Automatic

	column DS_GRAU_ESCOLARIDADE
		dataType: string
		lineageTag: 7b9717fc-ba13-4763-a629-2be1fa3218d2
		summarizeBy: none
		sourceColumn: DS_GRAU_ESCOLARIDADE

		annotation SummarizationSetBy = Automatic

	column CD_RACA_COR
		dataType: string
		lineageTag: 7dfd8db7-17d3-46f5-9fb6-e1fa57a2f6f8
		summarizeBy: none
		sourceColumn: CD_RACA_COR

		annotation SummarizationSetBy = Automatic

	column DS_RACA_COR
		dataType: string
		lineageTag: e86ced80-a6f0-4980-8835-e09dab703946
		summarizeBy: none
		sourceColumn: DS_RACA_COR

		annotation SummarizationSetBy = Automatic

	column CD_IDENTIDADE_GENERO
		dataType: string
		lineageTag: ec9b7e62-59fb-477c-91f9-89fc7f1b65c3
		summarizeBy: none
		sourceColumn: CD_IDENTIDADE_GENERO

		annotation SummarizationSetBy = Automatic

	column DS_IDENTIDADE_GENERO
		dataType: string
		lineageTag: 9c030122-914e-497f-b5b2-6165de9011af
		summarizeBy: none
		sourceColumn: DS_IDENTIDADE_GENERO

		annotation SummarizationSetBy = Automatic

	column CD_QUILOMBOLA
		dataType: string
		lineageTag: 6b1cf4a4-dc16-415e-985f-891c6cdc9072
		summarizeBy: none
		sourceColumn: CD_QUILOMBOLA

		annotation SummarizationSetBy = Automatic

	column DS_QUILOMBOLA
		dataType: string
		lineageTag: 6639f5b4-b0f0-4e5a-9207-454e2efcb03b
		summarizeBy: none
		sourceColumn: DS_QUILOMBOLA

		annotation SummarizationSetBy = Automatic

	column CD_INTERPRETE_LIBRAS
		dataType: string
		lineageTag: 4ec81e17-4adc-4dfb-a4a8-c1f30c4391a6
		summarizeBy: none
		sourceColumn: CD_INTERPRETE_LIBRAS

		annotation SummarizationSetBy = Automatic

	column DS_INTERPRETE_LIBRAS
		dataType: string
		lineageTag: ce33a05a-8446-400d-a5bf-b652e093d7e9
		summarizeBy: none
		sourceColumn: DS_INTERPRETE_LIBRAS

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES
		dataType: int64
		formatString: 0
		lineageTag: 3beb6c48-9319-46b7-943f-8ee2694ed84b
		summarizeBy: sum
		sourceColumn: QT_ELEITORES

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES_BIOMETRIA
		dataType: int64
		formatString: 0
		lineageTag: 080cdb97-5974-4d1c-bdf4-4ffe8962bb36
		summarizeBy: sum
		sourceColumn: QT_ELEITORES_BIOMETRIA

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES_DEFICIENCIA
		dataType: int64
		formatString: 0
		lineageTag: 1fd44c1d-112d-4156-8228-dbed4e93ece7
		summarizeBy: sum
		sourceColumn: QT_ELEITORES_DEFICIENCIA

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES_NOME_SOCIAL
		dataType: int64
		formatString: 0
		lineageTag: 8a7e8137-b0af-4707-ae5f-11bc499c8d1e
		summarizeBy: sum
		sourceColumn: QT_ELEITORES_NOME_SOCIAL

		annotation SummarizationSetBy = Automatic

	partition eleitorado_cruzado = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\TSE2026\dados\eleitorado_otimizado\eleitorado_perfil_uf_cruzado_2026.csv"),[Delimiter=";", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DT_GERACAO", type date}, {"HH_GERACAO", type time}, {"AA_ELEICAO", Int64.Type}, {"SG_UF", type text}, {"CD_GENERO", type text}, {"DS_GENERO", type text}, {"CD_ESTADO_CIVIL", type text}, {"DS_ESTADO_CIVIL", type text}, {"CD_FAIXA_ETARIA", type text}, {"DS_FAIXA_ETARIA", type text}, {"CD_GRAU_ESCOLARIDADE", type text}, {"DS_GRAU_ESCOLARIDADE", type text}, {"CD_RACA_COR", type text}, {"DS_RACA_COR", type text}, {"CD_IDENTIDADE_GENERO", type text}, {"DS_IDENTIDADE_GENERO", type text}, {"CD_QUILOMBOLA", type text}, {"DS_QUILOMBOLA", type text}, {"CD_INTERPRETE_LIBRAS", type text}, {"DS_INTERPRETE_LIBRAS", type text}, {"QT_ELEITORES", Int64.Type}, {"QT_ELEITORES_BIOMETRIA", Int64.Type}, {"QT_ELEITORES_DEFICIENCIA", Int64.Type}, {"QT_ELEITORES_NOME_SOCIAL", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

