table eleitorado_municipio
	lineageTag: b598dfda-bb1a-49f8-b460-2776d2d9f6bd

	column DT_GERACAO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d71d4a9-6302-47d3-8127-df1ea525082f
		summarizeBy: none
		sourceColumn: DT_GERACAO

		variation Variation
			isDefault
			relationship: fd3c44d7-dc58-4527-98f8-31e3b82eec64
			defaultHierarchy: LocalDateTable_8aeec30e-a40b-46dd-b16a-7bd53c488204.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HH_GERACAO
		dataType: dateTime
		formatString: Long Time
		lineageTag: b4937d8a-d87c-4dd1-8686-717358daec41
		summarizeBy: none
		sourceColumn: HH_GERACAO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column AA_ELEICAO
		dataType: int64
		formatString: 0
		lineageTag: 085ae909-c0e9-4f71-aed1-8110fae7634e
		summarizeBy: sum
		sourceColumn: AA_ELEICAO

		annotation SummarizationSetBy = Automatic

	column SG_UF
		dataType: string
		lineageTag: 49b1dec7-4597-44df-a9b3-3519659fb582
		summarizeBy: none
		sourceColumn: SG_UF

		annotation SummarizationSetBy = Automatic

	column CD_MUNICIPIO
		dataType: string
		lineageTag: e849316a-5832-4c1f-b7a8-e2415a39a30c
		summarizeBy: none
		sourceColumn: CD_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column NM_MUNICIPIO
		dataType: string
		lineageTag: 9bc47890-4015-463b-9293-4dcda04cb427
		summarizeBy: none
		sourceColumn: NM_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column DIMENSAO
		dataType: string
		lineageTag: 0e2c9094-1e1b-462a-9c9e-173010f0fb29
		summarizeBy: none
		sourceColumn: DIMENSAO

		annotation SummarizationSetBy = Automatic

	column CD_CATEGORIA
		dataType: string
		lineageTag: 4f3791bf-8ca2-43e7-9851-d5d55ae8f791
		summarizeBy: none
		sourceColumn: CD_CATEGORIA

		annotation SummarizationSetBy = Automatic

	column DS_CATEGORIA
		dataType: string
		lineageTag: 8b49fd0a-5666-4fef-95f1-49ac24a87c19
		summarizeBy: none
		sourceColumn: DS_CATEGORIA

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES
		dataType: int64
		formatString: 0
		lineageTag: 85298e92-f120-41ba-8adc-232420db3225
		summarizeBy: sum
		sourceColumn: QT_ELEITORES

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES_BIOMETRIA
		dataType: int64
		formatString: 0
		lineageTag: c59672a1-f9a9-407d-87ec-a86f5a813cd7
		summarizeBy: sum
		sourceColumn: QT_ELEITORES_BIOMETRIA

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES_DEFICIENCIA
		dataType: int64
		formatString: 0
		lineageTag: 76f3447e-1f42-4187-9d78-cabf7ba09457
		summarizeBy: sum
		sourceColumn: QT_ELEITORES_DEFICIENCIA

		annotation SummarizationSetBy = Automatic

	column QT_ELEITORES_NOME_SOCIAL
		dataType: int64
		formatString: 0
		lineageTag: f8affec3-429c-482b-8384-c2a58ce20ad7
		summarizeBy: sum
		sourceColumn: QT_ELEITORES_NOME_SOCIAL

		annotation SummarizationSetBy = Automatic

	column CH_MUNICIPIO
		dataType: string
		lineageTag: 8de4132d-7ff4-485b-8e31-f20a50de6783
		summarizeBy: none
		sourceColumn: CH_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	partition eleitorado_municipio = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\TSE2026\dados\eleitorado_otimizado\eleitorado_perfil_municipio_2026.csv"),[Delimiter=";", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DT_GERACAO", type date}, {"HH_GERACAO", type time}, {"AA_ELEICAO", Int64.Type}, {"SG_UF", type text}, {"CD_MUNICIPIO", type text}, {"NM_MUNICIPIO", type text}, {"DIMENSAO", type text}, {"CD_CATEGORIA", type text}, {"DS_CATEGORIA", type text}, {"QT_ELEITORES", Int64.Type}, {"QT_ELEITORES_BIOMETRIA", Int64.Type}, {"QT_ELEITORES_DEFICIENCIA", Int64.Type}, {"QT_ELEITORES_NOME_SOCIAL", Int64.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "CH_MUNICIPIO", each Text.From([SG_UF]) & "|" &
				Text.From([CD_MUNICIPIO])),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"CH_MUNICIPIO", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

